import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer"
import "bootstrap-icons/font/bootstrap-icons.css";
import { Poppins } from "next/font/google";

import { CartProvider } from "@/context/CartContext";
// import {Montserrat} from "next/font/google";
// next.config.js or app/layout.js
import "../app/fontawesome";



const poppins= Poppins ({subsets:["latin"], weight:["400","700"]});
// const montserrat= Montserrat ({subsets:["latin"], weight:["400","700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">

      <body className={poppins.className} >
      <CartProvider>
        <Header font={poppins}/>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
   
  );
}
