import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Poppins } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { CartProvider } from "@/context/CartContext";
import "../app/fontawesome";
import {  ClerkProvider } from '@clerk/nextjs'

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={poppins.className}>
      
          
        <CartProvider>
          <Header font={poppins} />
          {children}
          <Footer />
          <ToastContainer position="top-right" autoClose={3000} /> 
        </CartProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}