import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Poppins } from "next/font/google";

import { CartProvider } from "@/context/CartContext"; // Ensure the import path is correct
import "../app/fontawesome";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* Ensure the CartProvider wraps the content */}
        <CartProvider>
          <Header font={poppins} />
          {children} {/* This renders the dynamic page content */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
